### ISSUE TITLE
useUserDataLocalStorage hook

### ISSUE THREAD

**Issue by FUKA-INNOVATIONS** [FUKA-INNOVATIONS/locists#13]

**Comment by markoseppanen** [comment]
Should we rename this to useLocalStorage and this hook contain following functions:

- saveToLocalStorage (key,value) 
- loadFromLocalStorage (key) -> returns value

**Comment by FUKA-INNOVATIONS** [comment]
I already renamed it to useUserStorage but yes we can rename it again since useLocalStorage is more discriptive.
I added following functionalities but it is yet not complete:

I will understand the structure how its all implemented when you see all files and I will explain but there is userStorage.js with following content:




import AsyncStorage from '@react-native-async-storage/async-storage';

/*
 * Handling user data on user device
 * */

class UserStorage {

  // Get the access token from the storage
  async getToken() {
    try {
      const token = await AsyncStorage.getItem( 'token' );
      if ( token !== null ) {
        // value previously stored
        return token;
      }
    } catch ( e ) {
      // error reading value
    }
  }

  // Store token
  async setToken(token) {
    try {
      await AsyncStorage.setItem( 'token', token );
    } catch ( e ) {
      // saving error
    }
  }

  // Store access token
  async setUsername(username) {
    try {
      await AsyncStorage.setItem( 'username', username );
    } catch ( e ) {
      // saving error
    }
  }

  async getUsername() {
    try {
      const username = await AsyncStorage.getItem( 'username' );
      if ( username !== null ) {
        // value previously stored
        return username;
      }
    } catch ( e ) {
      // error reading value
    }
  }

}

export default UserStorage;

**Comment by FUKA-INNOVATIONS** [comment]
I will soon have the basic functionalities ready for user registration so I will push the new branch without merging and you will see how its done so far. or we can of course have a discord call ?

**Comment by FUKA-INNOVATIONS** [comment]
!! DO NOT MERGE !!  Push is only to see work done by now, still a lot to do..

Please check: https://github.com/FUKA-INNOVATIONS/locists/tree/issueAuthView
