### ISSUE TITLE
useMedia Hook

### ISSUE THREAD

**Issue by dfallow** [FUKA-INNOVATIONS/locists#23]
- [x] getAllMedia
- [x] getPostMedia
- [x] getEventMedia
- [x] getMediaById
- [x] postMedia

**Comment by FUKA-INNOVATIONS** [comment]
getPosts and getEvents done

**Comment by FUKA-INNOVATIONS** [comment]
const getEvents = async () => {
    const URL = `${ baseUrl }tags/${ eventTag }`;
    try {
      setLoadingEvents( true );
      const events = await axios.get( URL );
      setEvents( events.data );
      setLoadingEvents( false );
    } catch ( e ) {
      console.log( e );
    }
  };

  const getPosts = async () => {
    const URL = `${ baseUrl }tags/${ postTag }`;
    try {
      setLoadingEvents( true );
      const posts = await axios.get( URL );
      setPosts( posts.data );
      setLoadingPosts( false );
    } catch ( e ) {
      console.log( e );
    }
  };

**Comment by FUKA-INNOVATIONS** [comment]
Added to config.js

export const eventTag = 'locists_event';
export const postTag = 'locists_post';

**Comment by FUKA-INNOVATIONS** [comment]
getMediaById and getAllMedia complete
